version: 2

updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
      day: "monday"
      time: "05:00"
    open-pull-requests-limit: 15
    rebase-strategy: auto
    groups:
      dotnet:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"